name: CMake

on:
  push:
    branches: [ master, m-*, dougpuob-patch-*]
  pull_request:
    branches: [ master, m-* ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  Windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2 
      with:
        submodules: true

    - name: Config
      run: cmake -G "Visual Studio 16 2019" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/bin      
      run: |
        Release/test-derived-func-by-interface
        Release/test-class-by-test-fixture


  Linux:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2 
      with:
        submodules: true

    - name: Prepare
      run: sudo apt install ninja-build
    
    - name: Config
      run: cmake -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/bin      
      run: |
        Release/test-derived-func-by-interface
        Release/test-class-by-test-fixture

  MacOS:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2 
      with:
        submodules: true

    - name: Config
      run: cmake -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/bin      
      run: |
        Release/test-derived-func-by-interface
        Release/test-class-by-test-fixture
